if(NOT APPLE)
  set(CMAKE_SYSTEM_NAME Linux)
  set(CMAKE_PLATFORM Linux)
  set(CMAKE_SYSTEM_VERSION 1)
endif()

set(CMAKE_C_COMPILER $ENV{CC})
set(CMAKE_CXX_COMPILER $ENV{CXX})

set(CMAKE_FIND_ROOT_PATH $ENV{PREFIX} $ENV{BUILD_PREFIX}/$ENV{HOST}/sysroot)
if(APPLE)
  set(CMAKE_FIND_ROOT_PATH ${CMAKE_FIND_ROOT_PATH} /opt/local/MacOSX-SDKs/MacOSX10.10.sdk)
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

set(__CHAR_UNSIGNED___EXITCODE 1)
